/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppWorkspacesIndexRouteImport } from './routes/_app/workspaces/index'
import { Route as AppBoardsIndexRouteImport } from './routes/_app/boards/index'
import { Route as AppWorkspacesWorkspaceIdLayoutRouteImport } from './routes/_app/workspaces/$workspaceId/_layout'
import { Route as AppWorkspacesWorkspaceIdLayoutIndexRouteImport } from './routes/_app/workspaces/$workspaceId/_layout/index'
import { Route as AppWorkspacesWorkspaceIdLayoutSettingsIndexRouteImport } from './routes/_app/workspaces/$workspaceId/_layout/settings/index'
import { Route as AppWorkspacesWorkspaceIdLayoutMembersIndexRouteImport } from './routes/_app/workspaces/$workspaceId/_layout/members/index'
import { Route as AppWorkspacesWorkspaceIdLayoutBoardsIndexRouteImport } from './routes/_app/workspaces/$workspaceId/_layout/boards/index'
import { Route as AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRouteImport } from './routes/_app/workspaces/$workspaceId/_layout/boards/$boardId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppWorkspacesIndexRoute = AppWorkspacesIndexRouteImport.update({
  id: '/workspaces/',
  path: '/workspaces/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardsIndexRoute = AppBoardsIndexRouteImport.update({
  id: '/boards/',
  path: '/boards/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdLayoutRoute =
  AppWorkspacesWorkspaceIdLayoutRouteImport.update({
    id: '/workspaces/$workspaceId/_layout',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspacesWorkspaceIdLayoutIndexRoute =
  AppWorkspacesWorkspaceIdLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute =
  AppWorkspacesWorkspaceIdLayoutSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AppWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AppWorkspacesWorkspaceIdLayoutMembersIndexRoute =
  AppWorkspacesWorkspaceIdLayoutMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AppWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute =
  AppWorkspacesWorkspaceIdLayoutBoardsIndexRouteImport.update({
    id: '/boards/',
    path: '/boards/',
    getParentRoute: () => AppWorkspacesWorkspaceIdLayoutRoute,
  } as any)
const AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute =
  AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRouteImport.update({
    id: '/boards/$boardId/',
    path: '/boards/$boardId/',
    getParentRoute: () => AppWorkspacesWorkspaceIdLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/boards': typeof AppBoardsIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/workspaces/$workspaceId/': typeof AppWorkspacesWorkspaceIdLayoutIndexRoute
  '/workspaces/$workspaceId/boards': typeof AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute
  '/workspaces/$workspaceId/members': typeof AppWorkspacesWorkspaceIdLayoutMembersIndexRoute
  '/workspaces/$workspaceId/settings': typeof AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute
  '/workspaces/$workspaceId/boards/$boardId': typeof AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/boards': typeof AppBoardsIndexRoute
  '/workspaces': typeof AppWorkspacesIndexRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdLayoutIndexRoute
  '/workspaces/$workspaceId/boards': typeof AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute
  '/workspaces/$workspaceId/members': typeof AppWorkspacesWorkspaceIdLayoutMembersIndexRoute
  '/workspaces/$workspaceId/settings': typeof AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute
  '/workspaces/$workspaceId/boards/$boardId': typeof AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_app/boards/': typeof AppBoardsIndexRoute
  '/_app/workspaces/': typeof AppWorkspacesIndexRoute
  '/_app/workspaces/$workspaceId/_layout': typeof AppWorkspacesWorkspaceIdLayoutRouteWithChildren
  '/_app/workspaces/$workspaceId/_layout/': typeof AppWorkspacesWorkspaceIdLayoutIndexRoute
  '/_app/workspaces/$workspaceId/_layout/boards/': typeof AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute
  '/_app/workspaces/$workspaceId/_layout/members/': typeof AppWorkspacesWorkspaceIdLayoutMembersIndexRoute
  '/_app/workspaces/$workspaceId/_layout/settings/': typeof AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute
  '/_app/workspaces/$workspaceId/_layout/boards/$boardId/': typeof AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/boards'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/boards/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/boards'
    | '/workspaces'
    | '/workspaces/$workspaceId'
    | '/workspaces/$workspaceId/boards'
    | '/workspaces/$workspaceId/members'
    | '/workspaces/$workspaceId/settings'
    | '/workspaces/$workspaceId/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_auth'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_app/boards/'
    | '/_app/workspaces/'
    | '/_app/workspaces/$workspaceId/_layout'
    | '/_app/workspaces/$workspaceId/_layout/'
    | '/_app/workspaces/$workspaceId/_layout/boards/'
    | '/_app/workspaces/$workspaceId/_layout/members/'
    | '/_app/workspaces/$workspaceId/_layout/settings/'
    | '/_app/workspaces/$workspaceId/_layout/boards/$boardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/workspaces/': {
      id: '/_app/workspaces/'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boards/': {
      id: '/_app/boards/'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof AppBoardsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId/_layout': {
      id: '/_app/workspaces/$workspaceId/_layout'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces/$workspaceId/_layout/': {
      id: '/_app/workspaces/$workspaceId/_layout/'
      path: '/'
      fullPath: '/workspaces/$workspaceId/'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdLayoutIndexRouteImport
      parentRoute: typeof AppWorkspacesWorkspaceIdLayoutRoute
    }
    '/_app/workspaces/$workspaceId/_layout/settings/': {
      id: '/_app/workspaces/$workspaceId/_layout/settings/'
      path: '/settings'
      fullPath: '/workspaces/$workspaceId/settings'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdLayoutSettingsIndexRouteImport
      parentRoute: typeof AppWorkspacesWorkspaceIdLayoutRoute
    }
    '/_app/workspaces/$workspaceId/_layout/members/': {
      id: '/_app/workspaces/$workspaceId/_layout/members/'
      path: '/members'
      fullPath: '/workspaces/$workspaceId/members'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdLayoutMembersIndexRouteImport
      parentRoute: typeof AppWorkspacesWorkspaceIdLayoutRoute
    }
    '/_app/workspaces/$workspaceId/_layout/boards/': {
      id: '/_app/workspaces/$workspaceId/_layout/boards/'
      path: '/boards'
      fullPath: '/workspaces/$workspaceId/boards'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdLayoutBoardsIndexRouteImport
      parentRoute: typeof AppWorkspacesWorkspaceIdLayoutRoute
    }
    '/_app/workspaces/$workspaceId/_layout/boards/$boardId/': {
      id: '/_app/workspaces/$workspaceId/_layout/boards/$boardId/'
      path: '/boards/$boardId'
      fullPath: '/workspaces/$workspaceId/boards/$boardId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRouteImport
      parentRoute: typeof AppWorkspacesWorkspaceIdLayoutRoute
    }
  }
}

interface AppWorkspacesWorkspaceIdLayoutRouteChildren {
  AppWorkspacesWorkspaceIdLayoutIndexRoute: typeof AppWorkspacesWorkspaceIdLayoutIndexRoute
  AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute: typeof AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute
  AppWorkspacesWorkspaceIdLayoutMembersIndexRoute: typeof AppWorkspacesWorkspaceIdLayoutMembersIndexRoute
  AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute: typeof AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute
  AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute: typeof AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute
}

const AppWorkspacesWorkspaceIdLayoutRouteChildren: AppWorkspacesWorkspaceIdLayoutRouteChildren =
  {
    AppWorkspacesWorkspaceIdLayoutIndexRoute:
      AppWorkspacesWorkspaceIdLayoutIndexRoute,
    AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute:
      AppWorkspacesWorkspaceIdLayoutBoardsIndexRoute,
    AppWorkspacesWorkspaceIdLayoutMembersIndexRoute:
      AppWorkspacesWorkspaceIdLayoutMembersIndexRoute,
    AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute:
      AppWorkspacesWorkspaceIdLayoutSettingsIndexRoute,
    AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute:
      AppWorkspacesWorkspaceIdLayoutBoardsBoardIdIndexRoute,
  }

const AppWorkspacesWorkspaceIdLayoutRouteWithChildren =
  AppWorkspacesWorkspaceIdLayoutRoute._addFileChildren(
    AppWorkspacesWorkspaceIdLayoutRouteChildren,
  )

interface AppRouteChildren {
  AppBoardsIndexRoute: typeof AppBoardsIndexRoute
  AppWorkspacesIndexRoute: typeof AppWorkspacesIndexRoute
  AppWorkspacesWorkspaceIdLayoutRoute: typeof AppWorkspacesWorkspaceIdLayoutRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardsIndexRoute: AppBoardsIndexRoute,
  AppWorkspacesIndexRoute: AppWorkspacesIndexRoute,
  AppWorkspacesWorkspaceIdLayoutRoute:
    AppWorkspacesWorkspaceIdLayoutRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
